### ISSUE TITLE
Web UI stuck on 'Checking device connectivity'

### ISSUE THREAD

**Issue by zcduthie** [Leverege/microchip-pic-iot#2]
Web UI is currently broken - affected by Firebase Web SDK bug:
https://github.com/firebase/firebase-js-sdk/issues/2043
https://github.com/firebase/firebase-js-sdk/pull/2061

Gets stuck on 'Checking device connectivity', as the call to `this.firebase.database().ref('/.info/serverTimeOffset' ).once( 'value' )` in DeviceManager.js never returns a value.

Should update /setup/ui/package.json to a different version of Firebase, or wait for an update fix to come out (soon?)

**Comment by gregtoth** [comment]
I have the same problem. Messages are being published by the device and I can subscribe to them manually, but the Firebase app doesn't work and hangs at "Checking device connectivity" step.

**Comment by NMolargik** [comment]
Same issue here. Is there any workaround I can do manually?

**Comment by gregtoth** [comment]
> Same issue here. Is there any workaround I can do manually?

I fixed it myself by manually updating the ui npm packages and rebuilding everything.

**Comment by NMolargik** [comment]
> > Same issue here. Is there any workaround I can do manually?
> 
> I fixed it myself by manually updating the ui npm packages and rebuilding everything.

I'm a bit of a *noob*. Can you explain how exactly you did this?
